### ISSUE TITLE
Extension no longer in Chrome Webstore?

### ISSUE THREAD

**Issue by aldosch** [ao5357/development_favicon#11]
The webstore URL now 404s and the extension no longer appears in search results :(

https://chrome.google.com/webstore/detail/pdfbbnojibegcfdmhcccicmllbbkpeaf

**Comment by orschiro** [comment]
Confirmed. Why?

**Comment by sunnysingh** [comment]
@ao5357 Was the extension taken down? I was hoping to try it :(

**Comment by ao5357** [comment]
@sunnysingh Thank you for your interest in development_favicon!

I can confirm the extension has been out of the webstore for quite a while. At first it was due to me not updating the extension to comply with Chrome requirements that have shifted over time. After that I resigned the job on which gmail account I had originally registered the extension, so the original URL is no longer an option.

I will assign this issue to myself and make time in the next week to register the extension in the webstore.

**Comment by ao5357** [comment]
@aldosch @orschiro @sunnysingh I have submitted the extension to Google for their review prior to it getting posted to the webstore. Once it gets approved I will post the link here and update the documentation.

At the same time, I submitted my other extension ["page to wireframe"](https://github.com/ao5357/page-to-wireframe) for a similar review, in case you're interested. Clicking the button by the URL bar turns the page you're on into what looks like a wireframe:

![screenshot](https://user-images.githubusercontent.com/497987/77354138-a69a6380-6d18-11ea-9601-886acc77cf47.png)

I reckon it's more useful on the UX side of things than development, nevertheless I have a lot of fun pressing the button on various sites.

**Comment by orschiro** [comment]
Great thanks a lot Brad!

**Comment by ao5357** [comment]
The extension should now permanently be in the webstore under my personal account at https://chrome.google.com/webstore/detail/development-favicon/mopggoekgknbopeodgiodphdofgeojkb

Closing out the issue. Thank you for your interest in development_favicon!
